#!/usr/bin/env bash

check_factor() {
    args=("$@")
    num=${args[0]//:/}  # Remove the colon from the output

    if [ ${#args[@]} -eq 3 ]; then
        # If there are exactly 2 factors, use them directly
        p=${args[1]}
        q=${args[2]}
    else
        # Multiply factors to return exactly two factors
        p=1
        for ((i=1; i<=$((${#args[@]} / 2)); i++)); do
            p=$(($p * ${args[i]}))
        done
        q=$(($num / $p))
    fi

    echo "$num=$p*$q"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read -r i; do
        result=$(factor "$i")
        check_factor $result
    done < "$1"
fi
