#!/usr/bin/env bash

check_prime_factor() {
    num=$1
    for ((i=2; i*i<=num; i++)); do
        if ((num % i == 0)); then
            p=$i
            q=$((num / i))
            echo "$num=$p*$q"
            return 0
        fi
    done
    # If no factors were found, the number is prime
    echo "$num is prime"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r number; do
        check_prime_factor "$number"
    done < "$1"
fi
